name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      platform: aws
      region: us-east-1
      account_id: 123456789012

    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"

      - name: "Ejecutar script múltiple"
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

      - name: "Mostrando variables de entorno"
        run: |
          echo "Esto es el valor de plataforma: ${{ env.platform }}"
          echo "Esto es la región: ${{ env.region }}"
          echo "Esto es el valor de account ID: ${{ env.account_id }}"
